### ISSUE TITLE
Missing animal details

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-module-asm#1]
When looking at an animal's detail page it now shows up blank. We recently updated our version of ASM, so this may have introduced changes with the way the feed works:

https://bloomington.in.gov/animal-shelter/animals

**Comment by inghamn** [comment]
Yes the web service apis changed.  It affects the list of animals as well.

**Comment by inghamn** [comment]
Part of the web service api change was making this an authenticated call.  I think we need to manage permissions for the drupal user that will be making these calls to Animal Shelter.

**Comment by inghamn** [comment]
The production site has release 39 installed.  Release 39 is from Oct 2016, long before the web service was implemented in ASM.

**Comment by inghamn** [comment]
I've back ported the web service implementation to release 39, which we're running in production.  When we upgrade to a new release, we will need to update this Drupal module again.
