### ISSUE TITLE
Section to show stray animals

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-module-asm#3]
The shelter would like to set up a new section for stray animals that are currently in the facility. I believe these are classified as "Found animals" in ASM. 

For stray animals they would like to show: age, sex, breed, color, location found and photo if there is one in our system.

The layout could be similar to adoptable animals.

**Comment by inghamn** [comment]
"Found Animals" are in the database going back to the beginning of time.  Is there a date range we want to limit the display to?  Or do we need to provide fields for users to search for their lost animal?

**Comment by inghamn** [comment]
This implmentation depends on writing the webservice into ASM.

https://github.com/bobintetley/asm3/issues/329

One hold-up is the existing queries for found animals in ASM don't include all the information we want to display.  Implementing a json web service to output data from the existing queries didn't get us very far.

**Comment by inghamn** [comment]
Depends on #6

**Comment by inghamn** [comment]
We don't want a separate route for Stray animals.  Rather, we want strays to show up in the Found animals listing.   However, they should only show up in the Found animals as long as they are not yet up for adoption.  Once they are Adoptable, they should show up with all the other Adoptable animals.

**Comment by inghamn** [comment]
This question was asked on the ASM forums.
https://www.sheltermanager.com/site/en_forum.html#!/general:publish-on-hold-strays

There is an HTML page that can be displayed, but no JSON web service.
https://sheltermanager.com/repo/asm3_help/service.html#html-held-animals
