### ISSUE TITLE
Change search form to buttons or tabs

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-module-asm#4]
Since we only have 3 options in our search form to narrow results by type of animal (dog, cat, other), it would be easier to make these links to the filtered results. This way users could simply click the corresponding type, rather than using the select box and search button combo.

https://bloomington.in.gov/animal-shelter/animals

**Comment by rbdietz** [comment]
The first entry in the pulldown menu should be "All", Show All, or
something like that, not just a blank entry.





Rick Dietz

Director, Information & Technology Services Department
City of Bloomington, IN
dietzr@bloomington.in.gov
812.349.3485 Office
812.671.0776 Cell
bloomington.in.gov
