### ISSUE TITLE
Adoptable animal layout: 3 per row

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-module-asm#5]
[On the "Adoptable Animals" page](https://bloomington.in.gov/animal-shelter/animals), currently only two animals are displayed per row, even when the browser is expanded on a wider desktop view:

![screenshot-2018-1-9 adoptable animals city of bloomington indiana](https://user-images.githubusercontent.com/2225624/34726745-e68d495a-f522-11e7-8602-7ed6fe74c753.png)

Ideally we could fit 3 animals per row, even if the cards need to be slightly smaller.

**Comment by inghamn** [comment]
Fixed in the drupal-theme-cob
https://github.com/City-of-Bloomington/drupal-theme-cob/commit/dadda5d600fe8bcd27d0f1f55a8a460e599d97a7
