### ISSUE TITLE
Include links to animal filters on animal details page

### ISSUE THREAD

**Issue by charlesbrandt** [City-of-Bloomington/drupal-module-asm#9]
Now that we have a [twitter bot posting links directly to animal pages for the animal shelter's twitter feed](https://twitter.com/adopttodaybtown), it would be nice to include links back to the different animal types on the animal detail page. 

For example:
<img width="1269" alt="screen shot 2018-02-27 at 2 57 56 pm-2" src="https://user-images.githubusercontent.com/2225624/36751873-73d1232c-1bcf-11e8-93c0-113230eaab1d.png">

**Comment by inghamn** [comment]
Fixed in the COB theme

https://github.com/City-of-Bloomington/drupal-theme-cob/commit/c8a222eb096316c07015631523349cef99feeb54
